import os.path

TEST_DIR = os.path.abspath(os.path.dirname(__file__))

FTP_DIR = os.path.join(TEST_DIR, "data", "ftp")
FTP_ENS69 = os.path.join(FTP_DIR, "homo_sapiens", "GRCh37", "69")
FTP_ENS69_CDNA_FASTA = os.path.join(FTP_ENS69, "Homo_sapiens.GRCh37.cdna.all.fa.gz")
FTP_ENS69_DNA_FASTA = os.path.join(FTP_ENS69, "Homo_sapiens.GRCh37.dna.toplevel.fa.gz")
FTP_ENS69_NCRNA_FASTA = os.path.join(FTP_ENS69, "Homo_sapiens.GRCh37.ncrna.fa.gz")
FTP_ENS69_PEP_FASTA = os.path.join(FTP_ENS69, "Homo_sapiens.GRCh37.pep.all.fa.gz")
FTP_ENS69_GTF = os.path.join(FTP_ENS69, "Homo_sapiens.GRCh37.69.gtf.gz")
FTP_ENS100 = os.path.join(FTP_DIR, "homo_sapiens", "GRCh38", "100")
FTP_ENS100_CDNA_FASTA = os.path.join(FTP_ENS100, "Homo_sapiens.GRCh38.cdna.all.fa.gz")
FTP_ENS100_DNA_FASTA = os.path.join(FTP_ENS100, "Homo_sapiens.GRCh38.dna.toplevel.fa.gz")
FTP_ENS100_NCRNA_FASTA = os.path.join(FTP_ENS100, "Homo_sapiens.GRCh38.ncrna.fa.gz")
FTP_ENS100_PEP_FASTA = os.path.join(FTP_ENS100, "Homo_sapiens.GRCh38.pep.all.fa.gz")
FTP_ENS100_GTF = os.path.join(FTP_ENS100, "Homo_sapiens.GRCh38.100.gtf.gz")

CACHE_DIR = os.path.join(TEST_DIR, "data", "pyvariant")
TEST_ENS69 = os.path.join(CACHE_DIR, "homo_sapiens", "GRCh37", "69")
TEST_ENS69_CDNA_FASTA = os.path.join(TEST_ENS69, "Homo_sapiens.GRCh37.69.cdna.all.fa.gz")
TEST_ENS69_DNA_FASTA = os.path.join(TEST_ENS69, "Homo_sapiens.GRCh37.69.dna.toplevel.fa.gz")
TEST_ENS69_GTF = os.path.join(TEST_ENS69, "Homo_sapiens.GRCh37.69.gtf.gz")
TEST_ENS69_NCRNA_FASTA = os.path.join(TEST_ENS69, "Homo_sapiens.GRCh37.69.ncrna.fa.gz")
TEST_ENS69_PEP_FASTA = os.path.join(TEST_ENS69, "Homo_sapiens.GRCh37.69.pep.all.fa.gz")
TEST_ENS100 = os.path.join(CACHE_DIR, "homo_sapiens", "GRCh38", "100")
TEST_ENS100_CDNA_FASTA = os.path.join(TEST_ENS100, "Homo_sapiens.GRCh38.cdna.all.fa.gz")
TEST_ENS100_DNA_FASTA = os.path.join(TEST_ENS100, "Homo_sapiens.GRCh38.dna.toplevel.fa.gz")
TEST_ENS100_GTF = os.path.join(TEST_ENS100, "Homo_sapiens.GRCh38.100.gtf.gz")
TEST_ENS100_NCRNA_FASTA = os.path.join(TEST_ENS100, "Homo_sapiens.GRCh38.ncrna.fa.gz")
TEST_ENS100_PEP_FASTA = os.path.join(TEST_ENS100, "Homo_sapiens.GRCh38.pep.all.fa.gz")
TEST_ENS100_CANONICAL_TRANSCRIPT = os.path.join(TEST_ENS100, "canonical_transcript.txt")
TEST_ENS100_CONTIG_ALIAS = os.path.join(TEST_ENS100, "contig_alias.tsv")
TEST_ENS100_EXON_ALIAS = os.path.join(TEST_ENS100, "exon_alias.tsv")
TEST_ENS100_GENE_ALIAS = os.path.join(TEST_ENS100, "gene_alias.tsv")
TEST_ENS100_PROTEIN_ALIAS = os.path.join(TEST_ENS100, "protein_alias.tsv")
TEST_ENS100_TRANSCRIPT_ALIAS = os.path.join(TEST_ENS100, "transcript_alias.tsv")
