import ensembl_map


def test_init_ensembl_release():
    assert hasattr(ensembl_map, "EnsemblRelease")


def test_init_main():
    assert hasattr(ensembl_map, "all_contig_ids")
    assert hasattr(ensembl_map, "all_exon_ids")
    assert hasattr(ensembl_map, "all_gene_ids")
    assert hasattr(ensembl_map, "all_gene_names")
    assert hasattr(ensembl_map, "all_protein_ids")
    assert hasattr(ensembl_map, "all_transcript_ids")
    assert hasattr(ensembl_map, "all_transcript_names")
    assert hasattr(ensembl_map, "cdna_to_cdna")
    assert hasattr(ensembl_map, "cdna_to_dna")
    assert hasattr(ensembl_map, "cdna_to_exon")
    assert hasattr(ensembl_map, "cdna_to_protein")
    assert hasattr(ensembl_map, "cdna_to_rna")
    assert hasattr(ensembl_map, "cds_sequence")
    assert hasattr(ensembl_map, "contig_ids")
    assert hasattr(ensembl_map, "dna_sequence")
    assert hasattr(ensembl_map, "dna_to_cdna")
    assert hasattr(ensembl_map, "dna_to_dna")
    assert hasattr(ensembl_map, "dna_to_exon")
    assert hasattr(ensembl_map, "dna_to_protein")
    assert hasattr(ensembl_map, "dna_to_rna")
    assert hasattr(ensembl_map, "exon_ids")
    assert hasattr(ensembl_map, "exon_to_cdna")
    assert hasattr(ensembl_map, "exon_to_dna")
    assert hasattr(ensembl_map, "exon_to_exon")
    assert hasattr(ensembl_map, "exon_to_protein")
    assert hasattr(ensembl_map, "exon_to_rna")
    assert hasattr(ensembl_map, "gene_ids")
    assert hasattr(ensembl_map, "gene_names")
    assert hasattr(ensembl_map, "get_cdna")
    assert hasattr(ensembl_map, "get_dna")
    assert hasattr(ensembl_map, "get_exons")
    assert hasattr(ensembl_map, "get_genes")
    assert hasattr(ensembl_map, "get_transcripts")
    assert hasattr(ensembl_map, "is_contig")
    assert hasattr(ensembl_map, "is_exon")
    assert hasattr(ensembl_map, "is_gene")
    assert hasattr(ensembl_map, "is_protein")
    assert hasattr(ensembl_map, "is_transcript")
    assert hasattr(ensembl_map, "normalize_feature")
    assert hasattr(ensembl_map, "peptide_sequence")
    assert hasattr(ensembl_map, "protein_ids")
    assert hasattr(ensembl_map, "protein_to_cdna")
    assert hasattr(ensembl_map, "protein_to_dna")
    assert hasattr(ensembl_map, "protein_to_exon")
    assert hasattr(ensembl_map, "protein_to_protein")
    assert hasattr(ensembl_map, "protein_to_rna")
    assert hasattr(ensembl_map, "rna_sequence")
    assert hasattr(ensembl_map, "rna_to_cdna")
    assert hasattr(ensembl_map, "rna_to_dna")
    assert hasattr(ensembl_map, "rna_to_exon")
    assert hasattr(ensembl_map, "rna_to_protein")
    assert hasattr(ensembl_map, "rna_to_rna")
    assert hasattr(ensembl_map, "transcript_ids")
    assert hasattr(ensembl_map, "transcript_names")
