"""Type hints for position/variant objects."""
from typing import TypeVar

from .positions import (
    CdnaDeletion,
    CdnaDelins,
    CdnaDuplication,
    CdnaFusion,
    CdnaInsertion,
    CdnaPosition,
    CdnaSubstitution,
    DnaDeletion,
    DnaDelins,
    DnaDuplication,
    DnaFusion,
    DnaInsertion,
    DnaPosition,
    DnaSubstitution,
    ExonFusion,
    ExonPosition,
    ProteinDeletion,
    ProteinDelins,
    ProteinDuplication,
    ProteinFrameshift,
    ProteinFusion,
    ProteinInsertion,
    ProteinPosition,
    ProteinSubstitution,
    RnaDeletion,
    RnaDelins,
    RnaDuplication,
    RnaFusion,
    RnaInsertion,
    RnaPosition,
    RnaSubstitution,
)

PositionOrSmallVariantType = TypeVar(
    "PositionOrSmallVariantType",
    CdnaSubstitution,
    CdnaDeletion,
    CdnaDelins,
    CdnaDuplication,
    CdnaInsertion,
    CdnaPosition,
    DnaSubstitution,
    DnaDeletion,
    DnaDelins,
    DnaDuplication,
    DnaInsertion,
    DnaPosition,
    ExonPosition,
    ProteinSubstitution,
    ProteinDeletion,
    ProteinDelins,
    ProteinDuplication,
    ProteinFrameshift,
    ProteinInsertion,
    ProteinPosition,
    RnaSubstitution,
    RnaDeletion,
    RnaDelins,
    RnaDuplication,
    RnaInsertion,
    RnaPosition,
)

FusionType = TypeVar("FusionType", CdnaFusion, DnaFusion, ExonFusion, ProteinFusion, RnaFusion)
